# Generated by Django 3.1 on 2023-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='post title')),
                ('description', models.TextField(verbose_name='entry text')),
                ('author', models.CharField(max_length=100, verbose_name='Name author')),
                ('data', models.DateField(verbose_name='publication date')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Record',
            },
        ),
    ]
